name: fakestorebloc
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: null
  cupertino_icons: ^1.0.2
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
